### ISSUE TITLE
Mouse acceleration 

### ISSUE THREAD

**Issue by WoogieDoggie** [q-256/SkyBlockImproved#1]
I downloaded this mod and started using it but something felt slightly off and after some testing I figured out that it was something with the mouse in game. I tried to launch Minecraft without the mod and it was all good so I think the mod works as a mouse accelerator

**Comment by q-256** [comment]
I did some testing, and I have not been able to reproduce this bug. Are you absolutely certain it is this mod that is causing the issue? What version of Minecraft and Forge are you using? Does the mouse get sped up only in GUIs or in the actual game? What other mods are you using? What operating system are you using? Is there anything else I should know that would help me reproduce this bug?

**Comment by WoogieDoggie** [comment]
I was wrong I think it might have been another mod. Sorry for the inconvenience
